const M=window.NETA_METADATA,H=window.NETA_TOP_HOLDERS,I=window.NETA_ADDRESS_INDEX;
const S=M.stats||M;
const f=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:6}).format(Number(n||0));
const stake=h=>Number(h.neta_dao_staking||0),unstake=h=>Number(h.neta_dao_unstaking||0),claimable=h=>Number(h.neta_dao_claimable||0),lp=h=>Number(h.lp_neta||0);
const supply=Number(S.total_supply_neta||0),totalEntries=Number(S.economic_master_entries||0);
document.querySelector("#stats").innerHTML=[["TOTAL SUPPLY",S.total_supply_neta],["ECONOMIC HOLDERS",S.economic_master_entries],["JUNO CUSTODY",S.juno_custody_addresses],["OSMOSIS CUSTODY",S.osmosis_primary_state_addresses],["DAO STAKED",S.dao_active_staking_neta],["DAO UNSTAKING",S.dao_unstaking_neta],["DAO CLAIMABLE",S.dao_claimable_neta],["LP NETA",S.lp_neta]].map(x=>`<div class="stat"><div class="k">${x[0]}</div><div class="v">${f(x[1])}</div></div>`).join("");
document.querySelector("#updated").textContent="LAST UPDATED: "+new Date(M.generated_at).toLocaleString();
const sh=a=>a?(a.length>24?a.slice(0,12)+"…"+a.slice(-7):a):"—";
const allRows=(()=>{const seen=new Set(),rows=[];for(const h of Object.values(I||{})){const k=h.rank??`${h.juno_address||''}|${h.osmosis_address||''}`;if(seen.has(k))continue;seen.add(k);rows.push(h)}return rows.length?rows:H})();
let sortKey="total_neta",sortDir=-1;
const val=(h,k)=>k==="neta_dao_staking"?stake(h):k==="neta_dao_unstaking"?unstake(h):k==="neta_dao_claimable"?claimable(h):k==="lp_neta"?lp(h):Number(h[k]||0);
function sorted(){return [...allRows].sort((a,b)=>{const d=val(a,sortKey)-val(b,sortKey);return d?sortDir*d:Number(a.rank||0)-Number(b.rank||0)}).slice(0,100)}
function render(){const rows=sorted();document.querySelector("#rows").innerHTML=rows.map(h=>`<tr><td>${h.rank}</td><td class="address">${h.label?`<span class="label">${h.label}</span><br>`:""}${sh(h.juno_address||h.osmosis_address)}</td><td>${f(h.juno_neta)}</td><td>${f(h.osmosis_neta)}</td><td>${f(stake(h))}</td><td>${f(unstake(h))}</td><td>${f(claimable(h))}</td><td>${f(lp(h))}</td><td><b>${f(h.total_neta)}</b></td><td><span class="badge ${h.type}">${h.type.replaceAll("_"," ")}</span></td></tr>`).join("");document.querySelector("#mobileRows").innerHTML=rows.map(h=>`<div class="mobile-holder-card"><div class="mobile-holder-head"><div class="mobile-rank">#${h.rank}</div><div class="mobile-address">${h.label?`<div class="mobile-label">${h.label}</div>`:""}${sh(h.juno_address||h.osmosis_address)}</div><div class="mobile-total">${f(h.total_neta)}</div></div><div class="mobile-breakdown"><div class="mobile-cell"><div class="mk">JUNO</div><div class="mv">${f(h.juno_neta)}</div></div><div class="mobile-cell"><div class="mk">OSMOSIS</div><div class="mv">${f(h.osmosis_neta)}</div></div><div class="mobile-cell"><div class="mk">STAKED</div><div class="mv">${f(stake(h))}</div></div><div class="mobile-cell"><div class="mk">UNSTAKING</div><div class="mv">${f(unstake(h))}</div></div><div class="mobile-cell"><div class="mk">CLAIMABLE</div><div class="mv">${f(claimable(h))}</div></div><div class="mobile-cell"><div class="mk">LP NETA</div><div class="mv">${f(lp(h))}</div></div><div class="mobile-cell"><div class="mk">TYPE</div><div class="mv">${h.type.replaceAll("_"," ")}</div></div></div></div>`).join("");document.querySelectorAll("th.sortable").forEach(th=>{const active=th.dataset.sort===sortKey;th.classList.toggle("active-sort",active);th.textContent=th.textContent.replace(/ [↕↑↓]$/,'')+(active?(sortDir<0?' ↓':' ↑'):' ↕')})}
document.querySelectorAll("th.sortable").forEach(th=>{th.style.cursor="pointer";th.title="Click to sort";th.onclick=()=>{const k=th.dataset.sort;if(sortKey===k)sortDir*=-1;else{sortKey=k;sortDir=-1}render()}});render();
function topPercentText(rank,total){const pct=(rank/total)*100;if(pct<.1)return"TOP <0.1%";if(pct<1)return`TOP ${pct.toFixed(1)}%`;return`TOP ${Math.ceil(pct)}%`}
function lookup(){let q=document.querySelector("#q").value.trim().toLowerCase(),r=document.querySelector("#result"),h=I[q],def=document.querySelector("#rankPanelDefault"),panel=document.querySelector("#rankPanelResult");r.classList.remove("hidden");if(!h){r.innerHTML=`<div><div class="rank">NOT FOUND</div><div class="small">NO NETA BALANCE IN CURRENT SNAPSHOT</div></div>`;def.classList.remove("hidden");panel.classList.add("hidden");return}const topText=topPercentText(h.rank,totalEntries),supplyShare=supply?((h.total_neta/supply)*100):0;r.innerHTML=`<div><div class="rank">RANK #${h.rank}</div><div class="small">${h.label||h.type}</div></div><div class="rstat"><div class="small">TOTAL NETA</div><div class="big">${f(h.total_neta)}</div></div><div class="rstat"><div class="small">STAKED</div><div class="big">${f(stake(h))}</div></div><div class="rstat"><div class="small">UNSTAKING</div><div class="big">${f(unstake(h))}</div></div><div class="rstat"><div class="small">CLAIMABLE</div><div class="big">${f(claimable(h))}</div></div><div class="rstat"><div class="small">LP NETA</div><div class="big">${f(lp(h))}</div></div>`;def.classList.add("hidden");panel.classList.remove("hidden");panel.innerHTML=`<div class="rank-result-title">YOUR POSITION</div><div class="rank-big">#${h.rank}</div><div class="rank-percent">${topText} OF HOLDERS</div><div class="rank-grid"><div class="rank-mini"><div class="rk">TOTAL NETA</div><div class="rv">${f(h.total_neta)}</div></div><div class="rank-mini"><div class="rk">SUPPLY SHARE</div><div class="rv">${supplyShare.toFixed(4)}%</div></div><div class="rank-mini"><div class="rk">JUNO</div><div class="rv">${f(h.juno_neta)}</div></div><div class="rank-mini"><div class="rk">OSMOSIS</div><div class="rv">${f(h.osmosis_neta)}</div></div><div class="rank-mini"><div class="rk">DAO STAKED</div><div class="rv">${f(stake(h))}</div></div><div class="rank-mini"><div class="rk">DAO UNSTAKING</div><div class="rv">${f(unstake(h))}</div></div><div class="rank-mini"><div class="rk">DAO CLAIMABLE</div><div class="rv">${f(claimable(h))}</div></div><div class="rank-mini"><div class="rk">LP NETA</div><div class="rv">${f(lp(h))}</div></div></div><div class="share-line">Ranked #${h.rank} of ${f(totalEntries)} economic holder entries in the current snapshot.</div>`}
document.querySelector("#go").onclick=lookup;document.querySelector("#q").onkeydown=e=>{if(e.key==="Enter")lookup()};
