(()=>{
const $=s=>document.querySelector(s),OWNER="juno1z3xcalwan92yqxu9d406tlft9yy94jy8s5et57",CONTRACT="juno1vgh9dd4zs7gsg7p602pv5lw3xly6wq6xww3s98keddc6vqazga8qgnm4g8",RPCS=["https://juno.test.rpc.nodeshub.online","https://juno.rpc.t.stavr.tech"],RESTS=["https://juno.test.api.nodeshub.online","https://juno.api.t.stavr.tech"];
const CHAIN={chainId:"uni-7",chainName:"Juno Testnet",rpc:RPCS[0],rest:RESTS[0],bip44:{coinType:118},bech32Config:{bech32PrefixAccAddr:"juno",bech32PrefixAccPub:"junopub",bech32PrefixValAddr:"junovaloper",bech32PrefixValPub:"junovaloperpub",bech32PrefixConsAddr:"junovalcons",bech32PrefixConsPub:"junovalconspub"},currencies:[{coinDenom:"JUNOX",coinMinimalDenom:"ujunox",coinDecimals:6}],feeCurrencies:[{coinDenom:"JUNOX",coinMinimalDenom:"ujunox",coinDecimals:6,gasPriceStep:{low:.1,average:.2,high:.3}}],stakeCurrency:{coinDenom:"JUNOX",coinMinimalDenom:"ujunox",coinDecimals:6},features:["cosmwasm"]};
const state={address:null,eligibility:null,client:null,threads:[],selected:null,filter:"latest",busy:false};
const short=a=>`${a.slice(0,9)}…${a.slice(-6)}`,wait=ms=>new Promise(r=>setTimeout(r,ms)),deadline=(p,ms)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error("NETWORK TIMEOUT")),ms))]),encode=q=>encodeURIComponent(btoa(JSON.stringify(q))),indexer=e=>/transaction indexing is disabled/i.test(e?.message||String(e));
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n},when=t=>new Date(Number(t)*1000).toLocaleString();
async function query(q){for(const base of RESTS)try{const r=await deadline(fetch(`${base}/cosmwasm/wasm/v1/contract/${CONTRACT}/smart/${encode(q)}`,{cache:"no-store"}),15000);if(r.ok)return(await r.json()).data}catch{}throw new Error("UNI-7 CONTRACT QUERY FAILED")}
function shown(){return state.filter==="active"?state.threads.filter(t=>!t.closed):state.filter==="closed"?state.threads.filter(t=>t.closed):state.threads}
function renderList(){const list=$(".thread-list");list.replaceChildren();const rows=shown().filter(t=>!t.moderation?.hidden);list.classList.toggle("thread-list-empty",!rows.length);if(!rows.length){const e=node("div","thread-empty");e.append(node("span",null,"NO THREADS YET"),node("strong",null,"THE BOARD IS EMPTY."),node("small",null,"Be the first to open an on-chain conversation."));list.append(e);return}rows.forEach(t=>{const b=node("button",`thread-item${state.selected?.id===t.id?" active":""}`);b.type="button";b.append(node("span",`thread-state${t.closed?" closed":""}`,t.closed?"CLOSED":"ACTIVE"),node("strong",null,t.title),node("small",null,`${short(t.author)} · ${t.comment_count} COMMENTS · ${when(t.created_time)}`));b.onclick=()=>select(t.id);list.append(b)})}
function empty(){const p=$(".conversation-panel");p.className="conversation-panel conversation-empty";p.replaceChildren();const h=node("header","conversation-head"),d=node("div");d.append(node("span",null,"NETA SOCIALS"),node("h2",null,"No conversation selected."));h.append(d);const b=node("div","conversation-empty-body");b.append(node("span","empty-orb","∅"),node("strong",null,"NO MESSAGES TO DISPLAY"),node("p",null,"The first on-chain conversation will appear here."));p.append(h,b)}
function author(a,t,comment=false){const r=node("div",comment?"comment-meta":"thread-author"),o=node("span","address-orb",a.slice(5,7).toUpperCase()),m=node("div");m.append(node("strong",null,short(a)),node("small",null,when(t)));r.append(o,m);if(a===OWNER)r.append(node("span","owner-badge","OWNER"));return r}
function conversation(t,comments){const p=$(".conversation-panel");p.className="conversation-panel";p.replaceChildren();const h=node("header","conversation-head"),d=node("div");d.append(node("span",null,`THREAD #${t.id} · ${t.closed?"CLOSED":"ACTIVE"}`),node("h2",null,t.title));h.append(d);const mayManage=state.address&&(state.address===OWNER||(!t.closed&&state.address===t.author));if(mayManage){const manage=node("button","thread-state-action",t.closed?"REOPEN THREAD":"CLOSE THREAD");manage.type="button";manage.onclick=()=>setClosed(t,!t.closed,manage);h.append(manage)}p.append(h,author(t.author,t.created_time),node("div","thread-body",t.body),node("div","conversation-divider",`${comments.length} COMMENTS`));comments.filter(c=>!c.moderation?.hidden).forEach(c=>{const x=node("div","comment");x.append(author(c.author,c.created_time,true),node("p",null,c.body));p.append(x)});const f=node("form","comment-composer"),l=node("label",null,"ADD AN ON-CHAIN COMMENT"),a=node("textarea");a.id="comment-body";a.maxLength=1000;a.required=true;a.placeholder=t.closed?"THIS THREAD IS CLOSED":"Write a comment (1–1,000 characters)";a.disabled=t.closed||!state.eligibility?.can_post;const foot=node("div"),hint=node("span",null,t.closed?"THREAD CLOSED · OWNER CAN REOPEN":state.eligibility?.can_post?"30 SECOND POSTING COOLDOWN":"CONNECT AN ELIGIBLE WALLET"),send=node("button",null,"REVIEW IN KEPLR");send.type="submit";send.disabled=a.disabled;foot.append(hint,send);f.append(l,a,foot);f.onsubmit=comment;p.append(f)}
async function select(id){const t=state.threads.find(x=>x.id===Number(id));if(!t)return;state.selected=t;renderList();conversation(t,await query({comments:{thread_id:t.id,start_after:null,limit:100,descending:false}}))}
async function load(preferred){state.threads=await query({threads:{start_after:null,limit:30,descending:true}});renderList();const id=preferred??state.selected?.id??state.threads[0]?.id;if(id!==undefined)await select(id);else empty()}
async function access(wallet){state.address=wallet?.address?.toLowerCase()||null;state.eligibility=null;$("#new-thread").disabled=true;if(!state.address){$("#social-wallet").textContent="NOT CONNECTED";$("#social-stake").textContent="— NETA";$("#social-access").textContent="LOCKED";return}$("#social-wallet").textContent=short(state.address);$("#social-stake").textContent="CHECKING…";try{const e=state.eligibility=await query({comment_eligibility:{address:state.address}});$("#social-stake").textContent=e.owner_exempt?"OWNER EXEMPT":`${Number(e.staked)/1e6} NETA`;$("#social-access").textContent=e.can_post?"ELIGIBLE":e.banned?"BANNED":e.paused?"PAUSED":e.cooldown_remaining_seconds?`COOLDOWN ${e.cooldown_remaining_seconds}s`:"10 NETA REQUIRED";$("#social-access").dataset.state=e.can_post?"ready":"locked";$("#new-thread").disabled=!e.can_post}catch{$("#social-stake").textContent="QUERY FAILED";$("#social-access").textContent="LOCKED"}if(state.selected)select(state.selected.id).catch(error)}
async function signer(){if(state.client)return state.client;if(!state.address)throw new Error("CONNECT KEPLR FIRST");if(!window.keplr?.experimentalSuggestChain)throw new Error("KEPLR NOT FOUND");await window.keplr.experimentalSuggestChain(CHAIN);await window.keplr.enable("uni-7");const base=window.keplr.getOfflineSigner?.("uni-7")||window.getOfflineSigner?.("uni-7");if(!base)throw new Error("UNI-7 SIGNER UNAVAILABLE");const s={getAccounts:()=>base.getAccounts(),signDirect:(a,d)=>window.keplr.signDirect("uni-7",a,d,{preferNoSetFee:true}),signAmino:(a,d)=>window.keplr.signAmino("uni-7",a,d,{preferNoSetFee:true})};if((await s.getAccounts())[0]?.address!==state.address)throw new Error("CONNECTED WALLET CHANGED");for(const rpc of RPCS)try{state.client=await deadline(NetaSocialsTestnet.connect(rpc,s),45000);return state.client}catch{}throw new Error("ALL UNI-7 RPC ENDPOINTS FAILED")}
async function recover(find,label){for(let i=0;i<8;i++){if(i)await wait(2000);const rows=await query({threads:{start_after:null,limit:30,descending:true}});const hit=find(rows);if(hit)return hit}throw new Error(`${label} BROADCAST COULD NOT YET BE RECOVERED`)}
async function execute(msg,memo,recovery){try{return await NetaSocialsTestnet.execute(await signer(),state.address,CONTRACT,msg,memo)}catch(e){if(!indexer(e))throw e;await recovery();return{transactionHash:"RECOVERED_FROM_CHAIN"}}}
function error(e){const s=$("#social-live-status");s.textContent=e?.message||String(e);s.dataset.state="error"}
async function create(e){e.preventDefault();if(state.busy)return;const title=$("#thread-title").value.trim(),body=$("#thread-body").value.trim();if(!title||!body)return;state.busy=true;$("#thread-submit").disabled=true;$("#compose-status").textContent="CHECK KEPLR · NO FUNDS ARE ATTACHED";try{if(!(await query({comment_eligibility:{address:state.address}})).can_post)throw new Error("WALLET IS NOT ELIGIBLE");let found;await execute({create_thread:{title,body}},"NETA Socials uni-7 create thread",async()=>{found=await recover(r=>r.find(x=>x.author===state.address&&x.title===title&&x.body===body),"THREAD")});$("#draft-modal").hidden=true;await load(found?.id)}catch(x){$("#compose-status").textContent=x?.message||String(x)}finally{state.busy=false;$("#thread-submit").disabled=false}}
async function comment(e){e.preventDefault();if(state.busy)return;const body=$("#comment-body").value.trim(),id=state.selected.id;if(!body)return;const b=e.currentTarget.querySelector("button");state.busy=true;b.disabled=true;b.textContent="CHECK KEPLR";try{if(!(await query({comment_eligibility:{address:state.address}})).can_post)throw new Error("WALLET IS NOT ELIGIBLE");await execute({add_comment:{thread_id:id,body}},"NETA Socials uni-7 add comment",async()=>{for(let i=0;i<8;i++){if(i)await wait(2000);const rows=await query({comments:{thread_id:id,start_after:null,limit:100,descending:false}});if(rows.some(x=>x.author===state.address&&x.body===body))return}throw new Error("COMMENT BROADCAST COULD NOT YET BE RECOVERED")});await load(id);await access({address:state.address})}catch(x){error(x)}finally{state.busy=false;b.disabled=false;b.textContent="REVIEW IN KEPLR"}}
async function setClosed(thread,closed,button){if(state.busy)return;state.busy=true;button.disabled=true;button.textContent="CHECK KEPLR";try{await execute({set_thread_closed:{thread_id:thread.id,closed}},`NETA Socials uni-7 ${closed?"close":"reopen"} thread`,async()=>{await recover(rows=>rows.find(x=>x.id===thread.id&&x.closed===closed),"THREAD STATE")});await load(thread.id);$("#social-live-status").textContent=closed?"THREAD CLOSED ON UNI-7":"THREAD REOPENED ON UNI-7"}catch(x){error(x);button.disabled=false;button.textContent=closed?"CLOSE THREAD":"REOPEN THREAD"}finally{state.busy=false}}
$("#new-thread").onclick=()=>{if(!state.eligibility?.can_post)return;$("#thread-title").value="";$("#thread-body").value="";$("#compose-status").textContent="Nothing is sent until you approve the separate Keplr transaction.";$("#draft-modal").hidden=false;$("#thread-title").focus()};$("#draft-close").onclick=()=>{if(!state.busy)$("#draft-modal").hidden=true};$("#thread-form").onsubmit=create;$("#draft-modal").onclick=e=>{if(e.target===$("#draft-modal")&&!state.busy)$("#draft-modal").hidden=true};
document.querySelectorAll(".thread-filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".thread-filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;renderList()});
$("#add-juno-testnet").onclick=async e=>{const b=e.currentTarget;if(!window.keplr?.experimentalSuggestChain)return;b.disabled=true;try{await window.keplr.experimentalSuggestChain(CHAIN);b.textContent="· UNI-7 ADDED"}catch{b.textContent="· RETRY UNI-7"}finally{b.disabled=false}};
addEventListener("neta:wallet-connected",e=>access(e.detail));addEventListener("neta:wallet-position-updated",e=>access(e.detail));addEventListener("neta:wallet-disconnected",()=>{state.client?.disconnect?.();state.client=null;access(null)});access(window.NETA_WALLET_STATE);load().then(()=>$("#social-live-status").textContent="LIVE ON UNI-7 · CONTRACT 110").catch(error);
})();
