(()=>{
  const $=selector=>document.querySelector(selector),assets=$("#treasury-assets"),total=$("#treasury-total"),updated=$("#treasury-updated"),status=$("#treasury-live-status"),warning=$("#treasury-warning"),refresh=$("#treasury-refresh"),explorer=$("#treasury-explorer"),policy=$("#treasury-policy");
  if(!assets)return;
  const money=value=>value===null||value===undefined?"UNPRICED":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(value));
  const amount=value=>new Intl.NumberFormat("en-US",{maximumFractionDigits:6}).format(Number(value));
  const node=(tag,className,text)=>{const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element};
  let selectedDao=window.NETA_SELECTED_DAO||"neta-operations";
  function underlying(item){const wrap=node("div","lp-underlyings");wrap.append(node("span",null,"CONTAINS"));item.underlyings.forEach(part=>{const row=node("div","lp-underlying"),name=node("strong",null,part.symbol),quantity=node("small",null,`${amount(part.amount)} ${part.symbol}`),value=node("b",null,money(part.usd_value));row.append(name,quantity,value);wrap.append(row)});return wrap}
  function renderAsset(item,totalUsd){const row=node("article",`asset-row live ${item.type}`),dot=node("i",`asset-dot ${item.symbol.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`),identity=node("div"),name=node("strong",null,item.symbol),origin=item.type==="lp"?"LP TOKENS":item.origin==="IBC"?`IBC · ${item.base_denom||item.symbol}`:"JUNO NATIVE",quantity=node("small",null,`${amount(item.amount)} ${item.type==="lp"?"LP TOKENS":item.symbol} · ${origin}`),value=node("b",null,money(item.usd_value)),change=node("span",null,item.change_24h===null||item.change_24h===undefined?item.type==="lp"?"UNDERLYING VALUE":"—":`${Number(item.change_24h)>=0?"+":""}${Number(item.change_24h).toFixed(2)}%`),bar=node("div","asset-bar"),fill=node("i");if(Number(item.change_24h)>0)change.className="positive";if(Number(item.change_24h)<0)change.className="negative";fill.style.width=`${totalUsd&&item.usd_value?Math.max(1,Number(item.usd_value)/totalUsd*100):0}%`;bar.append(fill);identity.append(name,quantity);row.append(dot,identity,value,change,bar);if(item.type==="lp"&&Array.isArray(item.underlyings))row.append(underlying(item));return row}
  async function load(){
    const community=selectedDao==="juno",file=community?"juno-community-pool.json":"current.json";
    explorer.href=community?"https://juno-api.polkachu.com/cosmos/distribution/v1beta1/community_pool":"https://atomscan.com/juno/accounts/juno1excmamnysxujtd2hzm343nzdwch79y5cvk5h7w6uxlrt230xqwtqkmancl";
    explorer.textContent=community?"VIEW COMMUNITY POOL SOURCE ↗":"VIEW TREASURY ↗";
    policy.textContent=community?"The Juno Community Pool is read from the native distribution module; IBC assets remain separate positions.":"LP positions are shown as positions and valued from their proportional underlying reserves.";
    refresh.disabled=true;status.textContent=`REFRESHING ${community?"COMMUNITY POOL":"OPERATIONS"} SNAPSHOT`;try{const response=await fetch(`data/treasury/${file}?t=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`SNAPSHOT HTTP ${response.status}`);const data=await response.json();assets.replaceChildren();if(!Array.isArray(data.assets)||!data.assets.length)throw new Error(data.warnings?.[0]||"NO VERIFIED TREASURY ASSETS");const totalUsd=Number(data.total_usd||0);data.assets.sort((a,b)=>Number(b.usd_value||-1)-Number(a.usd_value||-1)).forEach(item=>assets.append(renderAsset(item,totalUsd)));total.textContent=money(data.total_usd);status.textContent=`${data.status} · ${community?"JUNO COMMUNITY POOL":"NETA OPERATIONS"} · BLOCK ${new Intl.NumberFormat("en-US").format(data.height)}`;updated.textContent=`BALANCES ${new Date(data.generated_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})} · PRICES ${data.price_source}`;warning.hidden=!data.warnings?.length;warning.textContent=(data.warnings||[]).join(" · ")}catch(error){assets.replaceChildren(node("div","treasury-loading error",`TREASURY DATA UNAVAILABLE · ${error.message}`));total.textContent="—";status.textContent="LIVE DATA UNAVAILABLE";updated.textContent="LAST VERIFIED SNAPSHOT COULD NOT BE LOADED";warning.hidden=true}finally{refresh.disabled=false}}
  window.addEventListener("neta:dao-change",event=>{selectedDao=event.detail.id;load()});
  refresh.addEventListener("click",load);load();setInterval(load,60000);
})();
